[pytest]
testpaths = src/test/python
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --html=ExtentReports/AutomationResult.html --self-contained-html -v
markers =
    google_search: Google search tests
    facebook_login: Facebook login tests
